on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare git
        run: |-
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: yarn install
      - name: Eslint & Prettier
        run: |
          npx eslint
          npx prettier --check .
      - name: Compile
        run: |
          yarn run compile
          yarn run compile-web
      - name: Test
        run: |
          xvfb-run -a yarn run test
          xvfb-run -a yarn run test-web
        if: runner.os == 'Linux'
      - name: Test
        run: |
          yarn run test
          yarn run test-web
        if: runner.os != 'Linux'
