on:
  push:
    branches:
      - releases/**
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: yarn install
      - name: Compile
        run: |
          yarn run compile
          yarn run compile-web
      - name: Test
        run: |
          xvfb-run -a yarn run test
          yarn run test-web
      - name: Publish
        if: success()
        run: yarn run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to Open VSX Registry
        if: success()
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
